---
- name: Do stuff on remote servers
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Install git
      ansible.builtin.package:
        name: git
        state: present

    - name: Install unzip
      ansible.builtin.package:
        name: unzip
        state: present


    - name: Create a new user
      ansible.builtin.user:
        name: gordon # case-sensitive
        state: present
        create_home: true
        shell: /bin/bash
        password: "Password99"

    - name: Ensure group for read-only access exists
      ansible.builtin.group:
        name: stash
        state: present

    - name: Add gordon to stash group
      ansible.builtin.user:
        name: gordon
        groups: stash
        append: true
    
    - name: Create /stash with correct owner/group and perms
      ansible.builtin.file:
        path: /stash
        state: directory
        owner: ubuntu
        group: stash
        mode: '2750'